{
 "title": "Crawler_ui metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "web_page_gen_time_count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_page_gen_time_count[5m])",
     "legendFormat": "web_page_gen_time_count"
    }
   ]
  },
  {
   "title": "web_page_gen_time_sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_page_gen_time_sum[1h])",
     "legendFormat": "web_page_gen_time_sum"
    }
   ]
  },
  {
   "title": "95-percental web_page_gen_time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket[5m])) by (le))",
     "legendFormat": "95-percental web_page_gen_time"
    }
   ]
  }
 ]
}