{
 "title": "Crawler metrics",
 "time": { "from": "2020-11-04T15:42:01.091Z", "to": "2020-11-04T19:42:01.091Z" },
 "panels": [
  {
   "title": "95-percental crawler_site_connection_time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket[5m])) by (le))",
     "legendFormat": "95-percental crawler_site_connection_time_bucket"
    }
   ]
  },
  {
   "title": "crawler_pages_parsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(crawler_pages_parsed[5m])", "legendFormat": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "crawler_page_parse_time_sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(crawler_page_parse_time_sum[5m])",
     "legendFormat": "crawler_page_parse_time_sum"
    }
   ]
  }
 ]
}