project_id               = "hallowed-zoo-291019"
region                   = "europe-north1-a"
zone                     = "europe-north1"
monitoring_service       = "none"
logging_service          = "none" 
