---
- name: Install docker-compose
  hosts: all
  become: true
  tasks:

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  # непосредственно установка
  - name: Install docker-compose
    apt:
      name: ['docker-compose']
      state: present
