---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: webserf
    component: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserf
      component: crawler
      release: {{ .Release.Name }} 
  template:
  template:
    metadata:
      name: crawler
      labels:
        app: webserf
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler
          protocol: TCP
        resources:
          requests:
            cpu: 500m
        env:
        - name: MONGO
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name)}}
        - name: RMQ_HOST
          value: {{ .Values.rabbitmqHost | default (printf "%s-rabbitmq" .Release.Name)}}
        - name: RMQ_QUEUE
          value: {{ .Values.queueName }}
        - name: RMQ_USERNAME
          value: {{ .Values.userName }} 
        - name: RMQ_PASSWORD 
          value: {{ .Values.password }} 
        - name: CHECK_INTERVAL
          value: {{ .Values.interval | default "100" | quote }}
        - name: EXCLUDE_URLS
          value: {{ .Values.excludeUrl }}
        args: [ {{ .Values.url }} ] 
